modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "terrain_slabs"
version = "${version}"
displayName = "Countered's Terrain Slabs"
authors = "Countered!"
description = '''
A Minecraft mod designed to smooth out terrain using custom slabs, improving the world generation and overall feel.
'''
logoFile = "icon.png"

[[dependencies.terrain_slabs]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.terrain_slabs]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.terrain_slabs]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "terrain_slabs.mixins.json"
[[mixins]]
config = "terrain_slabs.neoforge.mixins.json"